spring:
  application:
    name: storefront
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    protocol: smtp
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

snowflake:
  url: ${SNOWFLAKE_URL}
  user: ${SNOWFLAKE_USERNAME}
  private-key-file: ${SNOWFLAKE_PRIVATE_KEY_FILE}
  private-key-passphrase: ${SNOWFLAKE_RSA_KEY_PASSPHRASE}
  db: ${SNOWFLAKE_DATABASE}
  schema: ${SNOWFLAKE_SCHEMA}
  warehouse: ${SNOWFLAKE_WAREHOUSE}
  role: ${SNOWFLAKE_ROLE}


# App config
app:
  name: Product Ordering Portal
  base-url: http://localhost:3000
  token-expiry-hours: 24                    # 24 hours
  jwt:
    auth-secret: 65230cc35d4bcebcda389440296df7c2599037680d84a3047831e3e28dcb08902edbb5bf7051687c89fa7f3820161ee21f424042605c46a8abaf7d3947483ac6
    auth-expiration-ms: 14400000                                          # 4 hours
    refresh-secret: c1a0cc4a32134ef30bf00951ef9d260e79de196e5c12134a6997f5f46515f47b285fd9d3439d0fa649376d619dd2838c90253690610496d3fcf57a3c7954ca27
    refresh-expiration-ms: 86400000                                 # 24 hours

logging:
  level:
    org.springframework.security: DEBUG
    com.jacent.storefront: DEBUG
    net.snowflake: DEBUG
    com.zaxxer.hikari: DEBUG
    org.springframework.jdbc: DEBUG

# SpringDoc / Swagger UI
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true
    filter: true

opensearch:
  host: localhost
  port: 9200
  scheme: https
  username: admin
  password: ${OPENSEARCH_INITIAL_ADMIN_PASSWORD:admin}