spring:
  application:
    name: storefront
#  datasource:
#    url: jdbc:mysql://localhost:3306/storefront?useSSL=false&serverTimezone=UTC
#    username: root
#    password: JXWF7ikt2nSRReKg
#    driver-class-name: com.mysql.cj.jdbc.Driver
  datasource:
    url: ${SNOWFLAKE_DATABASE_URL}
    username: ${SNOWFLAKE_USERNAME}
    password: ${SNOWFLAKE_PASSWORD}
    driver-class-name: net.snowflake.client.jdbc.SnowflakeDriver

    hikari:
      connection-timeout: 60000
      maximum-pool-size: 10
      minimum-idle: 2
      connection-test-query: SELECT 1


# App config
app:
  jwt:
    auth-secret: 65230cc35d4bcebcda389440296df7c2599037680d84a3047831e3e28dcb08902edbb5bf7051687c89fa7f3820161ee21f424042605c46a8abaf7d3947483ac6
    auth-expiration-ms: 14400000                                          # 4 hours
    refresh-secret: c1a0cc4a32134ef30bf00951ef9d260e79de196e5c12134a6997f5f46515f47b285fd9d3439d0fa649376d619dd2838c90253690610496d3fcf57a3c7954ca27
    refresh-expiration-ms: 86400000                                 # 24 hours

logging:
  level:
    org.springframework.security: DEBUG
    com.jacent.storefront: DEBUG
    net.snowflake: DEBUG
    com.zaxxer.hikari: DEBUG
    org.springframework.jdbc: DEBUG

# SpringDoc / Swagger UI
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true
    filter: true