spring:
  application:
    name: storefront
  datasource:
    url: jdbc:mysql://localhost:3306/storefront?useSSL=false&serverTimezone=UTC
    username: root
    password: JXWF7ikt2nSRReKg
    driver-class-name: com.mysql.cj.jdbc.Driver
#    driver-class-name: net.snowflake.client.jdbc.SnowflakeDriver
